import '@vue/runtime-core';
import type SButton from './components/SButton.vue';
import type SActionIcon from './components/SActionIcon.vue';
import type STooltip from './components/STooltip.vue';
import type SNote from './components/SNote.vue';
import type SToggle from './components/SToggle.vue';
import type SToggleGroup from './components/SToggleGroup.vue';
import type SDialog from './components/SDialog.vue';
import type SImagePreview from './components/SImagePreview.vue';
import type STag from './components/STag.vue';
import type SStatus from './components/SStatus.vue';
import type SActionBar from './components/SActionBar.vue';
import type SProgressbar from './components/SProgressbar.vue';
import type SCopyText from './components/SCopyText.vue';
import type STimeline from './components/STimeline.vue';
import type SDashboard from './components/SDashboard.vue';
import type SDashboardItem from './components/SDashboardItem.vue';
import type SStat from './components/SStat.vue';
import type SFilterGroup from './components/SFilterGroup.vue';
import type SFilter from './components/SFilter.vue';
import type SPagination from './components/SPagination.vue';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        SButton: typeof SButton;
        's-button': typeof SButton;
        SActionIcon: typeof SActionIcon;
        's-action-icon': typeof SActionIcon;
        STooltip: typeof STooltip;
        's-tooltip': typeof STooltip;
        SNote: typeof SNote;
        's-note': typeof SNote;
        SToggle: typeof SToggle;
        's-toggle': typeof SToggle;
        SToggleGroup: typeof SToggleGroup;
        's-toggle-group': typeof SToggleGroup;
        SDialog: typeof SDialog;
        's-dialog': typeof SDialog;
        SImagePreview: typeof SImagePreview;
        's-image-preview': typeof SImagePreview;
        STag: typeof STag;
        's-tag': typeof STag;
        SStatus: typeof SStatus;
        's-status': typeof SStatus;
        SActionBar: typeof SActionBar;
        's-action-bar': typeof SActionBar;
        SProgressbar: typeof SProgressbar;
        's-progressbar': typeof SProgressbar;
        SCopyText: typeof SCopyText;
        's-copy-text': typeof SCopyText;
        STimeline: typeof STimeline;
        's-timeline': typeof STimeline;
        SDashboard: typeof SDashboard;
        's-dashboard': typeof SDashboard;
        SDashboardItem: typeof SDashboardItem;
        's-dashboard-item': typeof SDashboardItem;
        SStat: typeof SStat;
        's-stat': typeof SStat;
        SFilterGroup: typeof SFilterGroup;
        's-filter-group': typeof SFilterGroup;
        SFilter: typeof SFilter;
        's-filter': typeof SFilter;
        SPagination: typeof SPagination;
        's-pagination': typeof SPagination;
    }
}
export { };
