import '@vue/runtime-core';
import type SForm from './components/SForm.vue';
import type SFormRow from './components/SFormRow.vue';
import type SInput from './components/SInput.vue';
import type SSelect from './components/SSelect.vue';
import type SCheckbox from './components/SCheckbox.vue';
import type SCheckboxGroup from './components/SCheckboxGroup.vue';
import type SRadio from './components/SRadio.vue';
import type SRadioGroup from './components/SRadioGroup.vue';
import type SSwitch from './components/SSwitch.vue';
import type SDatePicker from './components/SDatePicker.vue';
import type SHtmlEditor from './components/SHtmlEditor.vue';
import type SUpload from './components/SUpload.vue';
import type SFilter from './components/SFilter.vue';
import type SFilterGroup from './components/SFilterGroup.vue';
import type STable from './components/STable.vue';
import type SPagination from './components/SPagination.vue';
import type STree from './components/STree.vue';
import type SColumnSettings from './components/SColumnSettings.vue';
import type SButton from './components/SButton.vue';
import type SActionIcon from './components/SActionIcon.vue';
import type STooltip from './components/STooltip.vue';
import type SNote from './components/SNote.vue';
import type SToggle from './components/SToggle.vue';
import type SToggleGroup from './components/SToggleGroup.vue';
import type SDialog from './components/SDialog.vue';
import type SImagePreview from './components/SImagePreview.vue';
import type STag from './components/STag.vue';
import type SStatus from './components/SStatus.vue';
import type SActionBar from './components/SActionBar.vue';
import type SProgressBar from './components/SProgressbar.vue';
import type SCopyText from './components/SCopyText.vue';
import type STimeline from './components/STimeline.vue';
import type SDashboard from './components/SDashboard.vue';
import type SDashboardItem from './components/SDashboardItem.vue';
import type SStat from './components/SStat.vue';
import type SCanvas from './components/SCanvas.vue';
import type SFooter from './components/SFooter.vue';
import type SDropdownMenu from './components/SDropdownMenu.vue';
import type SHorizontalMenu from './components/SHorizontalMenu.vue';
import type SVerticalMenu from './components/SVerticalMenu.vue';

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        SForm: typeof SForm;
        's-form': typeof SForm;
        SFormRow: typeof SFormRow;
        's-form-row': typeof SFormRow;
        SInput: typeof SInput;
        's-input': typeof SInput;
        SSelect: typeof SSelect;
        's-select': typeof SSelect;
        SCheckbox: typeof SCheckbox;
        's-checkbox': typeof SCheckbox;
        SCheckboxGroup: typeof SCheckboxGroup;
        's-checkbox-group': typeof SCheckboxGroup;
        SRadio: typeof SRadio;
        's-radio': typeof SRadio;
        SRadioGroup: typeof SRadioGroup;
        's-radio-group': typeof SRadioGroup;
        SSwitch: typeof SSwitch;
        's-switch': typeof SSwitch;
        SDatePicker: typeof SDatePicker;
        's-date-picker': typeof SDatePicker;
        SHtmlEditor: typeof SHtmlEditor;
        's-html-editor': typeof SHtmlEditor;
        SUpload: typeof SUpload;
        's-upload': typeof SUpload;
        SFilter: typeof SFilter;
        's-filter': typeof SFilter;
        SFilterGroup: typeof SFilterGroup;
        's-filter-group': typeof SFilterGroup;
        STable: typeof STable;
        's-table': typeof STable;
        SPagination: typeof SPagination;
        's-pagination': typeof SPagination;
        STree: typeof STree;
        's-tree': typeof STree;
        SColumnSettings: typeof SColumnSettings;
        's-column-settings': typeof SColumnSettings;
        SButton: typeof SButton;
        's-button': typeof SButton;
        SActionIcon: typeof SActionIcon;
        's-action-icon': typeof SActionIcon;
        STooltip: typeof STooltip;
        's-tooltip': typeof STooltip;
        SNote: typeof SNote;
        's-note': typeof SNote;
        SToggle: typeof SToggle;
        's-toggle': typeof SToggle;
        SToggleGroup: typeof SToggleGroup;
        's-toggle-group': typeof SToggleGroup;
        SDialog: typeof SDialog;
        's-dialog': typeof SDialog;
        SImagePreview: typeof SImagePreview;
        's-image-preview': typeof SImagePreview;
        STag: typeof STag;
        's-tag': typeof STag;
        SStatus: typeof SStatus;
        's-status': typeof SStatus;
        SActionBar: typeof SActionBar;
        's-action-bar': typeof SActionBar;
        SProgressBar: typeof SProgressBar;
        's-progress-bar': typeof SProgressBar;
        SCopyText: typeof SCopyText;
        's-copy-text': typeof SCopyText;
        STimeline: typeof STimeline;
        's-timeline': typeof STimeline;
        SDashboard: typeof SDashboard;
        's-dashboard': typeof SDashboard;
        SDashboardItem: typeof SDashboardItem;
        's-dashboard-item': typeof SDashboardItem;
        SStat: typeof SStat;
        's-stat': typeof SStat;
        SCanvas: typeof SCanvas;
        's-canvas': typeof SCanvas;
        SFooter: typeof SFooter;
        's-footer': typeof SFooter;
        SDropdownMenu: typeof SDropdownMenu;
        's-dropdown-menu': typeof SDropdownMenu;
        SHorizontalMenu: typeof SHorizontalMenu;
        's-horizontal-menu': typeof SHorizontalMenu;
        SVerticalMenu: typeof SVerticalMenu;
        's-vertical-menu': typeof SVerticalMenu;
    }
}
export { };
